name: 'Setup environment'
runs:
  using: 'composite'
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip pyinstaller
        pip install -r requirements.txt
      shell: bash
    - name: Build
      run: pyinstaller -F --add-data create_database.sql:. LogConverter.py
      shell: bash