# This is a basic workflow that is manually triggered

name: Build binaries

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip pyinstaller
        pip install -r requirements.txt
    - name: Build
      run: pyinstaller -F --add-data create_database.sql:. LogConverter.py
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: LogConverter.exe
        path: dist/LogConverter.exe
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip pyinstaller
        pip install -r requirements.txt
    - name: Build
      run: pyinstaller -F --add-data create_database.sql:. LogConverter.py
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: LogConverter
        path: dist/LogConverter